#!/bin/bash
#=====================================================================
# Install ArgoUML
#
# Version 1.0.0
# 18 May 2014
#=====================================================================

mkdir -p "$HOME/.argouml"
pushd "$HOME/.argouml"
wget http://argouml-downloads.tigris.org/nonav/argouml-0.34/ArgoUML-0.34.tar.gz
tar zxvf ArgoUML*
popd