#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Java development training courses.
#
# Arguments:
# (None)		
#
# Version: 1.1.0
# Date: 03-May-2014
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-java-dev-training-vm"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
sudo apt-get -y -f install aptitude curl

echo
echo '============================================================='
echo 'Installing Java Development Kit...'

sudo apt-get install -y -f openjdk-7-jdk

echo
echo '============================================================='
echo 'Installing Maven...'

sudo apt-get install -y -f maven

# =============================================================
# Installing Eclipse...

"./$COMMON_DIR/install_eclipse_kepler"

echo
echo '============================================================='
echo 'Installing RVM, Ruby, and Bundler...'

\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.0.0
gem install bundler

./verify


