#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Java development training courses.
#
# Arguments:
# (None)		
#
# Version: 1.1.0
# Date: 03-May-2014
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-java-dev-training-vm"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
sudo apt-get -y -f install aptitude curl

echo
echo '============================================================='
echo 'Installing Microsoft TrueType fonts...'

sudo apt-get install -y -f ttf-mscorefonts-installer

echo
echo '============================================================='
echo 'Installing Java Development Kit...'

sudo apt-get install -y -f openjdk-7-jdk

echo
echo '============================================================='
echo 'Installing Maven...'

sudo apt-get install -y -f maven

# =============================================================
# Installing Eclipse...

"./$COMMON_DIR/install_eclipse_kepler"

echo
echo '============================================================='
echo 'Installing RVM, Ruby, and Bundler...'

pushd "$HOME"
\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1
echo 'source "$HOME/.rvm/scripts/rvm"' >> .bashrc
. .bashrc
rvm --default use 2.1.1
gem install bundler
popd

echo
echo '============================================================='
echo 'Setting the desktop background image...'


# Install ArgoUML
./install_argouml

mkdir -p "$HOME/.backgrounds"
cp -f java-background.png "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/student/.backgrounds/java-background.png

./verify


