#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Cobol development.
#
# Arguments:
# (None)		
#
# Version: 2.0.0
# Date: 24-November-2020
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-cobol-dev-ubuntu"
export COMMON_DIR="provision-ubuntu-common"

git clone "https://github.com/neopragma/$COMMON_DIR"

echo
echo '============================================================='
echo 'Installing prerequisite packages to support GnuCOBOL'

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_aptitude"
sudo -E apt-get -y -f install libgmp3-dev libtool libdb-dev ncurses-dev libncurses-dev

echo
echo '============================================================='
echo 'Installing Berkeley DB 6.1.19'

mkdir -p "$HOME/.berkeley_db"
pushd "$HOME/.berkeley_db"
wget -O berkeley-db.tar.gz http://download.oracle.com/berkeley-db/db-6.1.19.tar.gz
tar xvfz berkeley-db.tar.gz
cd db-6.1.19
cd build_unix && ../dist/configure \
   --prefix=/usr      \
   --enable-compat185 \
   --enable-dbm       \
   --disable-static   \
   --enable-cxx &&
make
sudo make docdir=/usr/share/doc/db-6.1.19 install &&
sudo chown -v -R root:root                        \
      /usr/bin/db_*                          \
      /usr/include/db{,_185,_cxx}.h          \
      /usr/lib/libdb*.{so,la}                \
      /usr/share/doc/db-6.1.19
popd

echo
echo '============================================================='
echo 'Installing GnuCOBOL 3.1 RC1'

mkdir -p "$HOME/.cobol"
pushd "$HOME/.cobol"
wget -O gnucobol.tar.xz http://sourceforge.net/projects/gnucobol/files/latest/download/gnucobol-3.1-rc1.tar.xz/download
tar xvfz gnucobol.tar.xz
cd gnucobol-3.1-rc1
./configure --with-db
make
sudo make install
sudo ldconfig
