#!/bin/bash
#===============================================================================
# See if this instance appears to have everything installed as expected.
# This is for provision-cobol-dev-ubuntu.
#
# Version: 0.1 
# Date: 04 Aug 2014
# Author: Dave Nicolette
#===============================================================================

echo
echo '============================================================='
echo 'Verifying configuration of Cobol development environment...'

declare -i errors=0

declare -a pkg
pkg[${#pkg[@]}]='git'
pkg[${#pkg[@]}]='build-essential'
pkg[${#pkg[@]}]="linux-headers-$(uname -r)"
pkg[${#pkg[@]}]='dkms'
pkg[${#pkg[@]}]='python-software-properties'
pkg[${#pkg[@]}]='sublime-text-installer'

for name in "${pkg[@]}"
do
  if [[ -n "$(aptitude search ${name})" ]]; then 
      echo "package ${name} is installed"
  else
      echo "package ${name} was expected but is not installed - ERROR"
      errors="${errors}+1"
  fi 
done

declare -a app
app[${#app[@]}]="/usr/local/bin/cobc"

for name in "${app[@]}"
do
  if [[ -e "${name}" ]]; then 
      echo "${name} is present"
  else
      echo "${name} was expected but is not installed - ERROR"
      errors="${errors}+1"
  fi 
done

test "${errors}" -eq 0 && echo "...configuration is as expected." || echo "...${errors} expected package(s) or application(s) not found! Configuration may not function as desired." 
